name: "Setup Agentuity"
description: "Setup Agentuity CLI"
author: "Agentuity"
runs:
  using: "composite"
  steps:
    - uses: robinraju/release-downloader@v1
      with:
        repository: agentuity/cli
        fileName: "agentuity_Linux_x86_64.tar.gz"
        extract: true
        latest: true
        out-file-path: agentuity-release
    - name: add agentuity to PATH
      run: echo "$GITHUB_WORKSPACE/agentuity-release" >> $GITHUB_PATH
      shell: bash

