name: Test Setup Agentuity Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Test the action from the local repository
      - name: Test local action
        uses: ./
        with:
          api_key: ${{ secrets.AGENTUITY_API_KEY }}
          
      - name: Verify CLI works
        run: agentuity whoami
        shell: bash