name: Test Setup Agentuity Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Setup the CLI
      - name: Setup Agentuity CLI
        uses: ./
        with:
          api_key: ${{ secrets.AGENTUITY_API_KEY }}
      # Verify CLI works
      - name: Verify CLI works
        run: agentuity version
        shell: bash
          